🎨 display message even if there is an error in ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -106,22 +106,44 @@ jobs:
         flutter pub get
         echo -e "\e[1;32m✅ Dépendances récupérées avec succès !\e[0m"
     
+- name: Formater le code
+      id: format
+      continue-on-error: true
+      run: |
+        echo -e "\e[1;34m🖌️ Formatage du code...\e[0m"
+        OUTPUT=$(dart format --set-exit-if-changed . 2>&1)
+        echo "$OUTPUT" > format_output.txt
+        if [ $? -ne 0 ]; then
+          echo "format_error=true" >> $GITHUB_OUTPUT
+        fi
+        echo -e "\e[1;32m✅ Formatage du code terminé !\e[0m"
+
     - name: Analyser le code
-      id: code_analysis
+      id: analyze
+      continue-on-error: true
       run: |
         echo -e "\e[1;34m🔎 Analyse du code...\e[0m"
-        dart analyze > dart_analysis.txt
-        flutter analyze > flutter_analysis.txt
+        dart analyze > dart_analysis.txt 2>&1
+        flutter analyze > flutter_analysis.txt 2>&1
+        if [ $? -ne 0 ]; then
+          echo "analyze_error=true" >> $GITHUB_OUTPUT
+        fi
         echo -e "\e[1;32m✅ Analyse du code terminée !\e[0m"
 
-    - name: Exécuter les tests d'intégration
+    - name: Exécuter les tests
+      id: test
+      continue-on-error: true
       run: |
-        echo -e "\e[1;34m🧪 Exécution des tests d'intégration...\e[0m"
-        echo "espace réservé pour flutter drive --target=test_driver/app.dart"
-        echo -e "\e[1;32m✅ Tests d'intégration terminés avec succès !\e[0m"
+        echo -e "\e[1;34m🧪 Exécution des tests...\e[0m"
+        flutter test > test_output.txt 2>&1
+        if [ $? -ne 0 ]; then
+          echo "test_error=true" >> $GITHUB_OUTPUT
+        fi
+        echo -e "\e[1;32m✅ Tests terminés !\e[0m"
     
     - name: Vérification des vulnérabilités
-      id: vulnerability_check
+      id: vulnerability
+      continue-on-error: true
       run: |
         echo -e "\e[1;34m🛡️ Vérification des vulnérabilités connues...\e[0m"
         vulnerability_output=""
@@ -131,64 +153,49 @@ jobs:
             vulnerability_output+="⚠️ Vulnérabilité détectée pour $pkg: $result\n"
           fi
         done < <(flutter pub deps --json | jq -r '.packages[] | .name + "@" + .version')
-        echo "vulnerability_output<<EOF" >> $GITHUB_ENV
-        echo "$vulnerability_output" >> $GITHUB_ENV
-        echo "EOF" >> $GITHUB_ENV
+        echo "$vulnerability_output" > vulnerability_output.txt
+        if [ -n "$vulnerability_output" ]; then
+          echo "vuln_error=true" >> $GITHUB_OUTPUT
+        fi
         echo -e "\e[1;32m✅ Vérification des vulnérabilités terminée !\e[0m"
-    
+
     - name: Préparer le commentaire
+      if: always()
       id: prepare_comment
-      if: github.event_name == 'pull_request' && always()
       run: |
-        if [ "${{ job.status }}" == "success" ]; then
-          echo "comment_body=✅ Toutes les vérifications sont passées. Le code est propre et prêt à être fusionné." >> $GITHUB_OUTPUT
-        else
+        COMMENT_BODY=""
+        
+        if [[ "${{ steps.format.outcome }}" == "failure" || "${{ steps.analyze.outcome }}" == "failure" || "${{ steps.test.outcome }}" == "failure" || "${{ steps.vulnerability.outcome }}" == "failure" ]]; then
           COMMENT_BODY="## ❌ Échec des vérifications CI\n\n"
           
-          if [ -f "format_output.txt" ]; then
-            FORMAT_OUTPUT=$(cat format_output.txt)
-            if [ -n "$FORMAT_OUTPUT" ]; then
-              COMMENT_BODY+="### Formatage du code\n\`\`\`\n$FORMAT_OUTPUT\n\`\`\`\n\n"
-            fi
+          if [[ "${{ steps.format.outputs.format_error }}" == "true" ]]; then
+            COMMENT_BODY+="### Formatage du code\n\`\`\`\n$(cat format_output.txt)\n\`\`\`\n\n"
           fi
           
-          if [ -f "dart_analysis.txt" ]; then
-            DART_OUTPUT=$(cat dart_analysis.txt)
-            if [ -n "$DART_OUTPUT" ] && ! grep -q "No issues found" <<< "$DART_OUTPUT"; then
-              COMMENT_BODY+="### Analyse du code Dart\n\`\`\`\n$DART_OUTPUT\n\`\`\`\n\n"
-            fi
+          if [[ "${{ steps.analyze.outputs.analyze_error }}" == "true" ]]; then
+            COMMENT_BODY+="### Analyse du code Dart\n\`\`\`\n$(cat dart_analysis.txt)\n\`\`\`\n\n"
+            COMMENT_BODY+="### Analyse du code Flutter\n\`\`\`\n$(cat flutter_analysis.txt)\n\`\`\`\n\n"
           fi
           
-          if [ -f "flutter_analysis.txt" ]; then
-            FLUTTER_OUTPUT=$(cat flutter_analysis.txt)
-            if [ -n "$FLUTTER_OUTPUT" ] && ! grep -q "No issues found" <<< "$FLUTTER_OUTPUT"; then
-              COMMENT_BODY+="### Analyse du code Flutter\n\`\`\`\n$FLUTTER_OUTPUT\n\`\`\`\n\n"
-            fi
+          if [[ "${{ steps.test.outputs.test_error }}" == "true" ]]; then
+            COMMENT_BODY+="### Résultats des tests\n\`\`\`\n$(cat test_output.txt)\n\`\`\`\n\n"
           fi
           
-          if [ -f "test_output.txt" ]; then
-            TEST_OUTPUT=$(cat test_output.txt)
-            if [ -n "$TEST_OUTPUT" ] && grep -q "FAIL" <<< "$TEST_OUTPUT"; then
-              COMMENT_BODY+="### Résultats des tests\n\`\`\`\n$TEST_OUTPUT\n\`\`\`\n\n"
-            fi
-          fi
-          
-          if [ -f "vulnerability_output.txt" ]; then
-            VULN_OUTPUT=$(cat vulnerability_output.txt)
-            if [ -n "$VULN_OUTPUT" ]; then
-              COMMENT_BODY+="### Analyse de sécurité\n\`\`\`\n$VULN_OUTPUT\n\`\`\`\n\n"
-            fi
+          if [[ "${{ steps.vulnerability.outputs.vuln_error }}" == "true" ]]; then
+            COMMENT_BODY+="### Analyse de sécurité\n\`\`\`\n$(cat vulnerability_output.txt)\n\`\`\`\n\n"
           fi
           
           COMMENT_BODY+="Veuillez examiner ces résultats et apporter les améliorations nécessaires."
-          
-          echo "comment_body<<EOF" >> $GITHUB_OUTPUT
-          echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+        else
+          COMMENT_BODY="✅ Toutes les vérifications sont passées. Le code est propre et prêt à être fusionné."
         fi
+        
+        echo "comment_body<<EOF" >> $GITHUB_OUTPUT
+        echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
+        echo "EOF" >> $GITHUB_OUTPUT
 
     - name: Commenter les résultats de l'analyse
-      if: github.event_name == 'pull_request'
+      if: always() && github.event_name == 'pull_request'
       uses: peter-evans/create-or-update-comment@v3
       with:
         issue-number: ${{ github.event.pull_request.number }}
